# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'IssueHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IssueHub
  pod 'Alamofire', '~> 4.7.3'

  target 'IssueHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IssueHubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
