# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

def vendors_pods
  # normal pods
end

def session_pods
  pod 'GitHubAPI', :path => 'Local Pods/GitHubAPI'
  pod 'GitHubSession', :path => 'Local Pods/GitHubSession'
end

target 'IssueHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IssueHub
  vendors_pods
  session_pods

  target 'IssueHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IssueHubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
