# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IssueHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IssueHub
  pod 'DrawerController', '~> 4.0.0'

  target 'IssueHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IssueHubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
